# Example Inventory
all:
  hosts:
    us1:
      ansible_host: 192.168.0.101 # example ip
      ansible_user: user
      ansible_ssh_private_key_file: /home/user/.ssh/id_ed25519
  children:
    web:
      hosts:
        us1:
    # mailservers:
    #   hosts:
    #     mail:
